/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedFreelancerRouteImport } from './routes/_authenticated/freelancer'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFreelancerIndexRouteImport } from './routes/_authenticated/freelancer.index'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedFreelancerProfileRouteImport } from './routes/_authenticated/freelancer.profile'
import { Route as AuthenticatedFreelancerPortfolioRouteImport } from './routes/_authenticated/freelancer.portfolio'
import { Route as AuthenticatedFreelancerJobsRouteImport } from './routes/_authenticated/freelancer.jobs'
import { Route as AuthenticatedFreelancerApplicationsRouteImport } from './routes/_authenticated/freelancer.applications'
import { Route as AuthenticatedClientJobsRouteImport } from './routes/_authenticated/client.jobs'
import { Route as AuthenticatedClientCandidatesRouteImport } from './routes/_authenticated/client.candidates'
import { Route as AuthenticatedClientAnalyticsRouteImport } from './routes/_authenticated/client.analytics'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedClientJobsIndexRouteImport } from './routes/_authenticated/client.jobs.index'
import { Route as AuthenticatedClientJobsNewRouteImport } from './routes/_authenticated/client.jobs.new'
import { Route as AuthenticatedClientJobsJobIdRouteImport } from './routes/_authenticated/client.jobs.$jobId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFreelancerRoute = AuthenticatedFreelancerRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFreelancerIndexRoute =
  AuthenticatedFreelancerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFreelancerRoute,
  } as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedFreelancerProfileRoute =
  AuthenticatedFreelancerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedFreelancerRoute,
  } as any)
const AuthenticatedFreelancerPortfolioRoute =
  AuthenticatedFreelancerPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedFreelancerRoute,
  } as any)
const AuthenticatedFreelancerJobsRoute =
  AuthenticatedFreelancerJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedFreelancerRoute,
  } as any)
const AuthenticatedFreelancerApplicationsRoute =
  AuthenticatedFreelancerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedFreelancerRoute,
  } as any)
const AuthenticatedClientJobsRoute = AuthenticatedClientJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedClientRoute,
} as any)
const AuthenticatedClientCandidatesRoute =
  AuthenticatedClientCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientAnalyticsRoute =
  AuthenticatedClientAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedClientJobsIndexRoute =
  AuthenticatedClientJobsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientJobsRoute,
  } as any)
const AuthenticatedClientJobsNewRoute =
  AuthenticatedClientJobsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedClientJobsRoute,
  } as any)
const AuthenticatedClientJobsJobIdRoute =
  AuthenticatedClientJobsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AuthenticatedClientJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/client': typeof AuthenticatedClientRouteWithChildren
  '/freelancer': typeof AuthenticatedFreelancerRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/client/analytics': typeof AuthenticatedClientAnalyticsRoute
  '/client/candidates': typeof AuthenticatedClientCandidatesRoute
  '/client/jobs': typeof AuthenticatedClientJobsRouteWithChildren
  '/freelancer/applications': typeof AuthenticatedFreelancerApplicationsRoute
  '/freelancer/jobs': typeof AuthenticatedFreelancerJobsRoute
  '/freelancer/portfolio': typeof AuthenticatedFreelancerPortfolioRoute
  '/freelancer/profile': typeof AuthenticatedFreelancerProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/freelancer/': typeof AuthenticatedFreelancerIndexRoute
  '/client/jobs/$jobId': typeof AuthenticatedClientJobsJobIdRoute
  '/client/jobs/new': typeof AuthenticatedClientJobsNewRoute
  '/client/jobs/': typeof AuthenticatedClientJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/client/analytics': typeof AuthenticatedClientAnalyticsRoute
  '/client/candidates': typeof AuthenticatedClientCandidatesRoute
  '/freelancer/applications': typeof AuthenticatedFreelancerApplicationsRoute
  '/freelancer/jobs': typeof AuthenticatedFreelancerJobsRoute
  '/freelancer/portfolio': typeof AuthenticatedFreelancerPortfolioRoute
  '/freelancer/profile': typeof AuthenticatedFreelancerProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/freelancer': typeof AuthenticatedFreelancerIndexRoute
  '/client/jobs/$jobId': typeof AuthenticatedClientJobsJobIdRoute
  '/client/jobs/new': typeof AuthenticatedClientJobsNewRoute
  '/client/jobs': typeof AuthenticatedClientJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteWithChildren
  '/_authenticated/freelancer': typeof AuthenticatedFreelancerRouteWithChildren
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/client/analytics': typeof AuthenticatedClientAnalyticsRoute
  '/_authenticated/client/candidates': typeof AuthenticatedClientCandidatesRoute
  '/_authenticated/client/jobs': typeof AuthenticatedClientJobsRouteWithChildren
  '/_authenticated/freelancer/applications': typeof AuthenticatedFreelancerApplicationsRoute
  '/_authenticated/freelancer/jobs': typeof AuthenticatedFreelancerJobsRoute
  '/_authenticated/freelancer/portfolio': typeof AuthenticatedFreelancerPortfolioRoute
  '/_authenticated/freelancer/profile': typeof AuthenticatedFreelancerProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/freelancer/': typeof AuthenticatedFreelancerIndexRoute
  '/_authenticated/client/jobs/$jobId': typeof AuthenticatedClientJobsJobIdRoute
  '/_authenticated/client/jobs/new': typeof AuthenticatedClientJobsNewRoute
  '/_authenticated/client/jobs/': typeof AuthenticatedClientJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/client'
    | '/freelancer'
    | '/admin/reports'
    | '/admin/users'
    | '/client/analytics'
    | '/client/candidates'
    | '/client/jobs'
    | '/freelancer/applications'
    | '/freelancer/jobs'
    | '/freelancer/portfolio'
    | '/freelancer/profile'
    | '/admin/'
    | '/client/'
    | '/freelancer/'
    | '/client/jobs/$jobId'
    | '/client/jobs/new'
    | '/client/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin/reports'
    | '/admin/users'
    | '/client/analytics'
    | '/client/candidates'
    | '/freelancer/applications'
    | '/freelancer/jobs'
    | '/freelancer/portfolio'
    | '/freelancer/profile'
    | '/admin'
    | '/client'
    | '/freelancer'
    | '/client/jobs/$jobId'
    | '/client/jobs/new'
    | '/client/jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/client'
    | '/_authenticated/freelancer'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/users'
    | '/_authenticated/client/analytics'
    | '/_authenticated/client/candidates'
    | '/_authenticated/client/jobs'
    | '/_authenticated/freelancer/applications'
    | '/_authenticated/freelancer/jobs'
    | '/_authenticated/freelancer/portfolio'
    | '/_authenticated/freelancer/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
    | '/_authenticated/freelancer/'
    | '/_authenticated/client/jobs/$jobId'
    | '/_authenticated/client/jobs/new'
    | '/_authenticated/client/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/freelancer': {
      id: '/_authenticated/freelancer'
      path: '/freelancer'
      fullPath: '/freelancer'
      preLoaderRoute: typeof AuthenticatedFreelancerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelancer/': {
      id: '/_authenticated/freelancer/'
      path: '/'
      fullPath: '/freelancer/'
      preLoaderRoute: typeof AuthenticatedFreelancerIndexRouteImport
      parentRoute: typeof AuthenticatedFreelancerRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/freelancer/profile': {
      id: '/_authenticated/freelancer/profile'
      path: '/profile'
      fullPath: '/freelancer/profile'
      preLoaderRoute: typeof AuthenticatedFreelancerProfileRouteImport
      parentRoute: typeof AuthenticatedFreelancerRoute
    }
    '/_authenticated/freelancer/portfolio': {
      id: '/_authenticated/freelancer/portfolio'
      path: '/portfolio'
      fullPath: '/freelancer/portfolio'
      preLoaderRoute: typeof AuthenticatedFreelancerPortfolioRouteImport
      parentRoute: typeof AuthenticatedFreelancerRoute
    }
    '/_authenticated/freelancer/jobs': {
      id: '/_authenticated/freelancer/jobs'
      path: '/jobs'
      fullPath: '/freelancer/jobs'
      preLoaderRoute: typeof AuthenticatedFreelancerJobsRouteImport
      parentRoute: typeof AuthenticatedFreelancerRoute
    }
    '/_authenticated/freelancer/applications': {
      id: '/_authenticated/freelancer/applications'
      path: '/applications'
      fullPath: '/freelancer/applications'
      preLoaderRoute: typeof AuthenticatedFreelancerApplicationsRouteImport
      parentRoute: typeof AuthenticatedFreelancerRoute
    }
    '/_authenticated/client/jobs': {
      id: '/_authenticated/client/jobs'
      path: '/jobs'
      fullPath: '/client/jobs'
      preLoaderRoute: typeof AuthenticatedClientJobsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/candidates': {
      id: '/_authenticated/client/candidates'
      path: '/candidates'
      fullPath: '/client/candidates'
      preLoaderRoute: typeof AuthenticatedClientCandidatesRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/analytics': {
      id: '/_authenticated/client/analytics'
      path: '/analytics'
      fullPath: '/client/analytics'
      preLoaderRoute: typeof AuthenticatedClientAnalyticsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/client/jobs/': {
      id: '/_authenticated/client/jobs/'
      path: '/'
      fullPath: '/client/jobs/'
      preLoaderRoute: typeof AuthenticatedClientJobsIndexRouteImport
      parentRoute: typeof AuthenticatedClientJobsRoute
    }
    '/_authenticated/client/jobs/new': {
      id: '/_authenticated/client/jobs/new'
      path: '/new'
      fullPath: '/client/jobs/new'
      preLoaderRoute: typeof AuthenticatedClientJobsNewRouteImport
      parentRoute: typeof AuthenticatedClientJobsRoute
    }
    '/_authenticated/client/jobs/$jobId': {
      id: '/_authenticated/client/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/client/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedClientJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedClientJobsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClientJobsRouteChildren {
  AuthenticatedClientJobsJobIdRoute: typeof AuthenticatedClientJobsJobIdRoute
  AuthenticatedClientJobsNewRoute: typeof AuthenticatedClientJobsNewRoute
  AuthenticatedClientJobsIndexRoute: typeof AuthenticatedClientJobsIndexRoute
}

const AuthenticatedClientJobsRouteChildren: AuthenticatedClientJobsRouteChildren =
  {
    AuthenticatedClientJobsJobIdRoute: AuthenticatedClientJobsJobIdRoute,
    AuthenticatedClientJobsNewRoute: AuthenticatedClientJobsNewRoute,
    AuthenticatedClientJobsIndexRoute: AuthenticatedClientJobsIndexRoute,
  }

const AuthenticatedClientJobsRouteWithChildren =
  AuthenticatedClientJobsRoute._addFileChildren(
    AuthenticatedClientJobsRouteChildren,
  )

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientAnalyticsRoute: typeof AuthenticatedClientAnalyticsRoute
  AuthenticatedClientCandidatesRoute: typeof AuthenticatedClientCandidatesRoute
  AuthenticatedClientJobsRoute: typeof AuthenticatedClientJobsRouteWithChildren
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientAnalyticsRoute: AuthenticatedClientAnalyticsRoute,
  AuthenticatedClientCandidatesRoute: AuthenticatedClientCandidatesRoute,
  AuthenticatedClientJobsRoute: AuthenticatedClientJobsRouteWithChildren,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedFreelancerRouteChildren {
  AuthenticatedFreelancerApplicationsRoute: typeof AuthenticatedFreelancerApplicationsRoute
  AuthenticatedFreelancerJobsRoute: typeof AuthenticatedFreelancerJobsRoute
  AuthenticatedFreelancerPortfolioRoute: typeof AuthenticatedFreelancerPortfolioRoute
  AuthenticatedFreelancerProfileRoute: typeof AuthenticatedFreelancerProfileRoute
  AuthenticatedFreelancerIndexRoute: typeof AuthenticatedFreelancerIndexRoute
}

const AuthenticatedFreelancerRouteChildren: AuthenticatedFreelancerRouteChildren =
  {
    AuthenticatedFreelancerApplicationsRoute:
      AuthenticatedFreelancerApplicationsRoute,
    AuthenticatedFreelancerJobsRoute: AuthenticatedFreelancerJobsRoute,
    AuthenticatedFreelancerPortfolioRoute:
      AuthenticatedFreelancerPortfolioRoute,
    AuthenticatedFreelancerProfileRoute: AuthenticatedFreelancerProfileRoute,
    AuthenticatedFreelancerIndexRoute: AuthenticatedFreelancerIndexRoute,
  }

const AuthenticatedFreelancerRouteWithChildren =
  AuthenticatedFreelancerRoute._addFileChildren(
    AuthenticatedFreelancerRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
  AuthenticatedFreelancerRoute: typeof AuthenticatedFreelancerRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
  AuthenticatedFreelancerRoute: AuthenticatedFreelancerRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
